### ISSUE TITLE
Add command to enable/disable showing line endings

### ISSUE THREAD

**Issue by Otiel** [jeff-hykin/code-eol#3]
Instead of always having the line endings displayed, it would be good to have:
* A setting to show/hide end-of-line characters. For instance: `"code-eol.showEolCharacters": "true"/"false"`, and,
* A command (accessible from the palette) to show/hide end-of-line characters (by changing the above setting). For instance: `End of line: Toggle Render End of Line Characters`.

Of course, one shouldn't have to restart VS Code for the toggle to be active.

**Comment by jeff-hykin** [comment]
I agree this would be really useful as a key binding. Can't guarantee I'll be able to implement this soon, but I'll look into when I get a chance. 

If you're able to add it, I'll definitely merge you're changes into the code base.

**Comment by jeff-hykin** [comment]
Just an update. I looked into this a little more, I know what tools to use now and whenever I get a chance I'll implement it.

**Comment by jeff-hykin** [comment]
Alright went ahead and added this feature, the command is "Toggle (Show/Hide) Line Endings".
- Doesn't need to reload window (it toggles instantly)
- With it being a command, you can map it to any keybinding you want
- It stays toggled over window reload (it persistently saves whether its disabled/enabled)
- However, the setting doesn't show up in settings.json

**Comment by Otiel** [comment]
That's great, thanks a lot! Just tested it, it works perfectly. ❤️ 

--
Off-topic: neat notification, I didn't know VS Code could do that:
![image](https://user-images.githubusercontent.com/3851902/51046683-0a7ab580-15c7-11e9-83f0-99292b8384cf.png)
