### ISSUE TITLE
feature request: add style for each character

### ISSUE THREAD

**Issue by iricigor** [jeff-hykin/code-eol#5]
Would it be possible to add style settings to be also per character? For example, I want to have one color for Newline and the other for Crlf.

I presume it would be also good to keep default settings for less complexity and backward compatibility. So just to add a check if there are no specific settings, use default one.

Anyway, great work :thumbsup:

**Comment by jeff-hykin** [comment]
Next update, I'll see if I can add this! I don't think it'll be too difficult, and I agree I can keep the settings in such a way that it won't break backwards compatibility.

Update: this might be coming around spring break time or early summer of 2019

**Comment by jeff-hykin** [comment]
Alright this was just implemented! Let me know if you have any problems with it.
