### ISSUE TITLE
Seems to break Visual Code's input dialog

### ISSUE THREAD

**Issue by montagne27** [jeff-hykin/code-eol#8]
Hello,

"code-eol 2019" seems to break Visual Code's input dialog. By input dialog, I mean the dialog which some extensions use in order to request a text parameter from the user, and which looks like this:

```
[         ]
Press 'Enter' to confirm your input or 'Escape' to cancel
```

For example, the ["Filter Line"](https://github.com/everettjf/vscode-filter-line) extension uses the input dialog like this:

![screen capture](https://raw.githubusercontent.com/everettjf/vscode-filter-line/master/img/bystring.gif)

When "code-eol 2019" is active, the input dialog never shows.

**Comment by jeff-hykin** [comment]
I'll try to reproduce it this weekend.
This is really strange though, code-eol 2019 doesn't use the input dialog at all so I don't know why/how it would effect other extensions.

**Comment by jeff-hykin** [comment]
I'm unable to reproduce this, is it still an issue for you?

**Comment by montagne27** [comment]
I think my computer is too slow, and the input dialog times out. "code-eol 2019" extension is just the heaviest extension I have, but another heavy extension would also break the input dialog. If I restart Visual Code while "code-eol 2019" is still installed, the problem gets solved temporarily and then reappears. I mark this ticket as closed. Thank you for investigating, and sorry for wasting your time!
